wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1673284725.726984
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 13
      - 16
      - 23
      4: 3.8.10
      5: 0.13.4
      8:
      - 1
      - 5
architecture:
  desc: null
  value: my U-NET
batch_size:
  desc: null
  value: 128
dataset:
  desc: null
  value: Blender_Dataset
dataset_size:
  desc: null
  value: 10000
epochs:
  desc: null
  value: 30
learning_rate:
  desc: null
  value: 0.001
loss:
  desc: null
  value: BCEWLogits
